apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-complete-production-e2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: complete-prodcution-e2e-pipeline
  template:
    metadata:
      labels:
        run: complete-prodcution-e2e-pipeline
    spec:
      containers:
      - name: complete-prodcution-e2e-pipeline
        image: ay0mikun/complete-prodcution-e2e-pipeline:1.0.0-9
        resources:
          limits:
            memory: "256Mi"
            cpu: "500"
        ports:
          - containerPort: 8080
